import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Fragment, useState } from 'react';
import {http} from '../helpers/RestInterceptor'
import {IAlbum} from '../models/models'
import { Image, Table } from 'react-bootstrap';

const Home: NextPage = () => {

  const [albums, setAlbums] = useState<IAlbum[]>([]);

  http
    .get<IAlbum[]>('https://jsonplaceholder.typicode.com/albums?_start=0&_limit=5',)
    .then((response) => {
      setAlbums(response.data);
    })
    


  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
       

      <Table striped hover >
          <tbody>
        {albums.map((album: IAlbum, index: number) => {
              return  <tr>
                          <td> 
                            <Image
                                    src=
                            "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png"
                                    thumbnail
                                  /></td>
                           
                          <td> 
                            <p>{album.userId}</p>
                            <p>{album.id}</p>
                            <p>{album.title}</p>
                          </td>
                        </tr>
                     
            })}
         

          </tbody>
        </Table>
      </main>

    </div>
  )
}

export default Home
