import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Fragment, useState } from 'react';
import {http} from '../helpers/RestInterceptor'
import {IAlbum} from '../models/models'
import { Image } from 'react-bootstrap';

const Home: NextPage = () => {

  const [albums, setAlbums] = useState<IAlbum[]>([]);

  http
    .get<IAlbum[]>('https://jsonplaceholder.typicode.com/albums?_start=0&_limit=5',)
    .then((response) => {
      setAlbums(response.data);
    })
    


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
        {albums.map((album: IAlbum, index: number) => {
              return  <div  className={styles.card}>
                        <div style={{float: 'left'}}>
                          <h2><Image
        src=
"https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png"
        roundedCircle
      /></h2>
                          <p>{album.userId}</p>
                          <p>{album.id}</p>
                          <p>{album.title}</p>
                        </div>
                      </div>
            })}
         

          
        </div>
      </main>

    </div>
  )
}

export default Home
